kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx

spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80 # port in the service
      targetPort: 80 # port in the pod
